steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA',
      ]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    args: 
        [
          "deploy", "releases", "create", "release-$_RELEASE_TIMESTAMP",
          "--delivery-pipeline", "cloud-run-pipeline",
          "--region", "${_LOCATION}",
          "--images", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
        ]
    entrypoint: gcloud
substitutions:
  _SERVICE_NAME: hello-world-service
  _LOCATION: us-central1
