apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: cloud-run-app
profiles:
- name: DEV
  manifests:
    rawYaml:
    - deploy-dev.yaml
- name: qa
  manifests:
    rawYaml:
    - deploy-qa1.yaml
- name: prod
  manifests:
    rawYaml:
    - deploy-uat.yaml
deploy:
  cloudrun: {}